require("vinicius.plugins-setup")
require("vinicius.core.options")
require("vinicius.core.keymaps")
require("vinicius.core.colorscheme")
require("vinicius.plugins.comment")
require("vinicius.plugins.nvim-tree")
require("vinicius.plugins.lualine")
require("vinicius.plugins.telescope")
require("vinicius.plugins.nvim-cmp")
require("vinicius.plugins.lsp.mason")
require("vinicius.plugins.lsp.lspsaga")
require("vinicius.plugins.lsp.lspconfig")
require("vinicius.plugins.lsp.null-ls")
require("vinicius.plugins.autopairs")
require("vinicius.plugins.treesitter")
require("vinicius.plugins.gitsigns")

